seed: 42
device: cuda:0
num_steps_per_env: 24
max_iterations: 2000
empirical_normalization: null
obs_groups:
  policy:
  - policy
  critic:
  - policy
clip_actions: null
save_interval: 50
experiment_name: unitree_go2_flat
run_name: pretrain
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
class_name: MBPOOnPolicyRunner
policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  noise_std_type: scalar
  actor_obs_normalization: false
  critic_obs_normalization: false
  actor_hidden_dims:
  - 128
  - 128
  - 128
  critic_hidden_dims:
  - 128
  - 128
  - 128
  activation: elu
algorithm:
  class_name: MBPOPPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.005
  num_learning_epochs: 5
  num_mini_batches: 4
  policy_learning_rate: 0.001
  system_dynamics_learning_rate: 0.0003
  system_dynamics_weight_decay: 1.0e-06
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.0
  system_dynamics_forecast_horizon: 8
  system_dynamics_loss_weights:
    state: 1.0
    sequence: 2.0
    bound: 1.0
    kl: 0.05
    extension: 1.0
    contact: 2.0
    termination: 2.0
  system_dynamics_num_mini_batches: 32
  system_dynamics_mini_batch_size: 300
  system_dynamics_replay_buffer_size: 1500
  system_dynamics_num_eval_trajectories: 100
  system_dynamics_len_eval_trajectory: 400
  system_dynamics_eval_traj_noise_scale:
  - 0.1
  - 0.2
  - 0.4
  - 0.5
  - 0.8
system_dynamics:
  ensemble_size: 5
  history_horizon: 32
  architecture_config:
    type: rnn
    rnn_type: gru
    rnn_num_layers: 2
    rnn_hidden_size: 256
    state_mean_shape:
    - 128
    state_logstd_shape:
    - 128
    extension_shape:
    - 128
    contact_shape:
    - 128
    termination_shape:
    - 128
  freeze_auxiliary: false
imagination:
  num_envs: 0
  num_steps_per_env: 0
  max_episode_length: 0
  command_resample_interval_range: null
  uncertainty_penalty_weight: -0.0
  state_normalizer:
    mean:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - -1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    std:
    - 0.5
    - 0.5
    - 0.1
    - 0.3
    - 0.3
    - 0.5
    - 0.02
    - 0.02
    - 0.04
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 2.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
    - 8.0
  action_normalizer:
    mean:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    std:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
load_system_dynamics: false
system_dynamics_load_path: null
system_dynamics_warmup_iterations: 0
system_dynamics_num_visualizations: 4
system_dynamics_state_idx_dict:
  $v$\n$[m/s]$:
  - 0
  - 1
  - 2
  $\omega$\n$[rad/s]$:
  - 3
  - 4
  - 5
  $g$\n$[1]$:
  - 6
  - 7
  - 8
  $q$\n$[rad]$:
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  $\dot{q}$\n$[rad/s]$:
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  $\tau$\n$[Nm]$:
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
pca_obs_buf_size: 10000
