FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
    ZeroTorque:
      id: 4
  Passive:
    key_transitions:
      FixStand: f         # [F] fix stand
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    key_transitions:
      Passive: p          # [P] back to passive
      Velocity: v         # [V] start policy
      ZeroTorque: e       # [E] emergency stop
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      [0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 1.0, -1.5, -0.1, 1.0, -1.5],
    ]
  Velocity:
    key_transitions:
      Passive: p          # [P] back to passive
      ZeroTorque: e       # [E] emergency stop
    policy_dir: config/policy/velocity/v0
  ZeroTorque:
    key_transitions:
      Passive: r          # [R] resume to passive
